manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tjallemaal
      url-base: https://github.com/tjallemaal
  projects:
    - name: zmk-config
      remote: tjallemaal
      revision: adv360-led
      import: app/build.yml
  self:
    path: config
